export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORY = "GET_CATEGORY";
export const ADD_CATEGORIES = "ADD_CATEGORIES";
export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const DELETE_CATEGORIES = "DELETE_CATEGORIES";

export const GET_WORDS = "GET_WORDS";
export const GET_WORD = "GET_WORD";
export const ADD_WORDS = "ADD_WORDS";
export const UPDATE_WORDS = "UPDATE_WORDS";
export const DELETE_WORDS = "DELETE_WORDS";
